resources:
- manager.yaml
images:
- name: controller
  newName: ghcr.io/grafana/operator
  newTag: latest
replicas:
- name: controller-manager
  count: 2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
