version: 1.0

indicators:
  - environment: &env
      - GOBIN=${{CF_VOLUME_PATH}}/go/bin
      - GOPATH=${{CF_VOLUME_PATH}}/go
      - PATH=$PATH:$GOBIN
  - working_directory: &dir ${{clone} 
  - image: &image golang:1.17

stages:
  - clone
  - generate
  - deploy

steps:
  clone:
    title: Cloning repository
    stage: clone
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: capsule
  
  generate:
    title: Generate Manifests
    stage: generate
    environment: *env
    working_directory: *dir
    image: *image
    commands:
      - make kubectl
      - make kustomize
      - make manifests

  deploy:
    title: Deploy K-6 Operator
    type: parallel
    stage: deploy
    steps:
      useast1: &deploy
        title: Deploy us-east-1
        image: *image
        environment:
          - context=test-use1
          <<: *env
        working_directory: *dir
        commands:
          - apk add --no-cache make
          - make install
          - make deploy
      useast2:
        title: Deploy us-east-2
        environment:
          - context=test-use2
        <<: *deploy
      uswest1:
        title: Deploy us-west-1
        environment:
          - context=test-usw1
        <<: *deploy
      uswest2:
        title: Deploy us-west-2
        environment:
          - context=test-usw2
        <<: *deploy
    when:
      branch:
        only:
          - deploy

  # notify:
